export const advancedEquipment = [
  'Glorious Intervenor',
  "Sorcerer's Wands",
  'Dragonheart Shield',
  'Wyrmstrike Mace',
  'Cyclone Bow',
  'Bane Axe',
  'Gloves of Haste',
  'Spectral Shroud',
  'Staff of the Sea',
  "Stormcaller's Shield",
  'Bone Spear',
  'Celestial Mail',
  'Gravestone Sword',
  'Rulebreaker',
  'Eldritch Pendant',
  'Circlet of Curses',
  'Silver Seraphim Mace',
  'Rune Crown',
  'Eternal Disemboweler',
  'Triquetra Bracelet',
  'Golden Cuirass',
  'The Nord Sword',
  'Jade Skull Guardian',
  'Unicorn’s Wisdom',
  'Halamina Shortbow',
  'Axe of Annihilation',
  'Nirvana Longsword',
  'Magic Flute',
  'Digital Cannon',
  "Magnificent Demon's Blade",
];

export default advancedEquipment;
