export const advancedSpells = [
  'Meteor Strike',
  'Dimension Door',
  'Consume Magic',
  'Shield of Light',
  'Voidblast',
  'Arcane Explosion',
  'Guardian of the Forest',
  'Whisper of Death',
  'Graviton Surge',
  'Havoc Bolt',
  'Shadowform',
  'Burning Ground',
  'Reanimation',
  'Icy Winds',
  'Ragnarok',
  'Mind Bomb',
  'Time Stop',
  'Tear Drop',
  'Phantom Attack',
  'Absolute Zero',
  'Elemental Nova',
  'Holy Light',
  'Elemental Lash',
  'Phoenix Rise',
  'Blood Curse',
  'Spirit Purge',
  'Chain Curse',
  'Ice Age',
  'Ancient Defense',
  'Plague',
  'Blackout',
  'Chains of Enslavement',
  'Unholy Sacrifice',
  'Acid Rain',
  'Dark Reflection',
  'Void Shield',
  'Crystal Rain',
  'Implosion',
  'Divine Wind',
  'Entangle',
  'Eternal Flames',
  'Soul Steal',
  'Slow Poison',
  'Freyablast',
  "Einherjar's Gaze",
  'Gravitational Collapse',
  'Faith in Flames',
  'Tombstone',
  'Fury of the Cyclone',
  'Clone',
];

export default advancedSpells;
