export const advancedCreatures = [
  'Archangel',
  'Black Dragon',
  'Gold Dragon',
  'Silver Dragon',
  'Abyssal Demon',
  'Celestial Demon',
  'Angelic Bard',
  'Chimeric Beast',
  'Phoenix Queen',
  'Desolate Dragon',
  'Gorgon Queen',
  'Kraken Overlord',
  'Sandworm',
  'Mindflayer',
  'Giant Mummy',
  'Living Corpse',
  'Thunderbird',
  'Harpy Queen',
  'Mermaid Queen',
  'Griffon Rider',
  'Frost Giant',
  "Titan's Titan",
  'Demon Paladin',
  'Marshmallow Monster',
  'Wraith King',
  'Hydra Overlord',
  'Chiron the Centaur',
  'Sphinx Queen',
  'Infernal Succubus',
  'Valkyrie',
  'Fluxquid',
  'Purple Gayansura Doeltuk',
  'Spooky Skeleton',
  'Orb of Seers',
  'Sylvan Argonaut',
  'Gladiator Angel',
  'Kraken Champion',
  'Dragonslayer',
  'Demi-Lich',
  'Exarch Quester',
  'Mechanical Dragon',
  'Tusker',
  'Garuda Rider',
  'Leviathan Queen',
  'Tyrannical T-Rex',
  'Griffon Lord',
  'Treefolk Giant',
  'Lamia Empress',
  'Pygmy Orc',
  'Gargoyle Lord',
  'Dragoon',
  'Mu-Aryansura Neotuac (the horned one)',
  'Sea Dragon',
  'Ice Behemoth',
  'Dark Mermaid',
  'Thunder Rhino',
  'Great Leviathan Enforcer',
  'Gargoyle Warlock',
  'Succubus Empress',
  'Sky Whales',
  'Samuarian',
  'Raptor Riders',
  'Ape Overlord',
  'Fae Prince',
  'Grenadier of the Dreamweavers',
  'Doppelganger',
  'Elementofragment',
  'Sun Titan',
  'Storm Giant',
  'Frost Succubus',
  'Demon Mage',
  'Winged Gorgon Queen',
  'Hydra Champion',
  'Copper Snake',
  'Athena (The Greek Goddess)',
  'Succubus Princess',
  'Dark Elf Warlock',
  'Crystal Golem',
  'Holy Mummy',
  'Mermaid Sorceress',
  'Chimera Overlord',
  'Necrotic Corps',
  'Dragon Emperor',
  'Dragon Summoner',
  'Infernal Angel',
  'Frost Golem',
  'Divine Unicorn',
  'Malicious Troll',
  'Leviathan Champion',
  'Frost Witch',
  'Egyptian God',
  'Spirit Wolf',
  'Gladiators Battalion',
  'Sea Serpent Lord',
  'Inferno Behemoth',
  'Undead Valkyrie',
  'Ogre Warlord',
  'Mountain Giantess',
  'Lamp Adze',
  'Succubus Empress II',
];

export default advancedCreatures;
