export const basicSpells = [
  'Fireball',
  'Ice Shard',
  'Healing Blessing',
  'Thunder Bolt',
  'Chain Lightning',
  'Teleportation',
  'Mind Control',
  'Protection Ward',
  'Energy Drain',
  'Elemental Ray',
  'Levitation',
  'Invisibility',
  'Light Beam',
  'Magic Missile',
  'Animal Summon',
  'Fairy Dust',
  'Poison Dart',
  'Slow Time',
  'Explosion',
  'Acid Burst',
  'Flame Guard',
  'Freeze',
  'Tracelessness',
  'Mind Blast',
  'Hypnosis',
  'Cold Snap',
  'Sleep',
  'Shockwave',
  'Continuous Magic Missile',
  'Fear',
  'Binding',
  'Dark Energy',
  'Phantom',
  'Blinding Light',
  'Dragonfire',
  'Elemental Shield',
  'Divine Smite',
  'Haste',
  'Paralysis',
  'Stone Curse',
  'Piercing Light',
  'Power Word Kill',
  'Rebuke',
  'Regeneration',
  'Searing Light',
  'Shock Sphere',
  'Sound Burst',
  'Wall of Fire',
  'Water Walking',
  'Conjure Magical Shield',
  'Bless',
  'Disease',
  'Enlarge',
  'Confuse',
  'Gravity Field',
  'Flight',
  'Force Bolt',
  'Giant’s Strength',
  'Heal Undead',
  'Holy Aura',
  'Ice Spike',
  'Passwall',
  'Poison Cloud',
  'Sleep Cloud',
  'Steelheart',
  'Stone Form',
  'Thunder Clap',
  'Chain Heal',
  'Control Fire',
  'Deflect Magic',
  'Divine Intervention',
  'Fiery Blast',
  'Ice Armor',
  'Lightning Strike',
  'Magic Shield',
];

export default basicSpells;
