export const basicCreatures = [
  'Soldier',
  'Archer',
  'Scout',
  'Warrior',
  'Knight',
  'Cleric',
  'Magician',
  'White Mage',
  'Black Mage',
  'Red Mage',
  'Paladin',
  'Mage Knight',
  'Shadow Mage',
  'Gunner',
  'Hitman',
  'Golem',
  'Elemental',
  'Giant',
  'Ogre',
  'Cyclops',
  'Manticore',
  'Hydra',
  'Bugbear',
  'Behemoth',
  'Troll',
  'Mermaid',
  'Kraken',
  'Sea Serpent',
  'Shark',
  'Siren',
  'Fairy',
  'Pixie',
  'Unicorn',
  'Phoenix',
  'Griffin',
  'Chimera',
  'Dragon',
  'Wyrm',
  'Gargoyle',
  'Harpy',
  'Minotaur',
  'Sphynx',
  'Cerberus',
  'Hellhound',
  'Demon',
  'Imp',
  'Satyr',
  'Healer',
  'Thief',
  'Rogue',
  'Shade',
  'Ghost',
  'Banshee',
  'Specter',
  'Shadow',
  'Dark Knight',
  'Djinni',
  'Wraith',
  'Revenant',
  'Leviathan',
  'Wisp',
  'Poltergeist',
  'Wendigo',
  'Ooze',
  'Slime',
  'Gelatin',
  'Carnivorous Plant',
  'Dryad',
  'Simulacrum',
  'Vampire',
  'Necromancer',
  'Spectral Hound',
  'Skeleton',
  'Zombie',
  'Ghoul',
  'Gnome',
  'Undead Warrior',
  'Undead Archer',
  'Mummy',
  'Harbinger',
  'Gorgon',
  'Medusa',
  'Basilisk',
  'Titan',
  "Titan's Minion",
  "Titan's Heir",
  'Anointed Knight',
  'Mystic Botanical',
  'Elf',
  'Dwarf',
  'Ice Golem',
  'Stone Golem',
  'Fire Golem',
  'Dark Sorcerer',
  'Fire Elemental',
  'Water Elemental',
  'Electric Elemental',
  'Air Elemental',
  'Sand Elemental',
  'Fog Elemental',
  'Dark Wizard',
  'Lightning Catcher',
  'Ice Catcher',
  'Warlock',
  'Magical Beast Tamer',
  'Mystic Beast Quiz',
  'Winged Steed',
  'Behemoth Lord',
  'Beastman',
  'Ghoul Warrior',
  'Lascar',
  'Wyvern',
  'Harpy Assassin',
  'Mimic',
  'Hobgoblin',
  'Skeletal Soldier',
  'Mummy Warrior',
  'Zombie King',
  'Scorpion',
  'Seta',
  'Succubus',
  'Angel',
  'Winged Champion',
  'Peacekeeping Cannon',
  'Stormlighter',
  'Molten Lava Elemental',
  'Crystal Serpent',
  'Phantom Stag',
  'Sky Bison',
  'Scorched Salamander',
  'Devouring Void',
  'Giant Clam',
  'Shifting Sands Djinn',
  'Alien Grunt',
  'Azure Lion',
  'Obsidian Crusader',
  'Evasive Shrimp',
  'Bloodhaze Spider',
  'Ornery Goat',
  'Frozen Husk',
  'Steel Beetle',
  'Fiery Phoenix',
  'Night Terror',
  'Thunderbird Sentinel',
  'Arctic Arcticwolf',
  'Storm-Wracked Kraken',
  'Veiled Witch',
  'Felguard Captain',
  'Cursed Pegasus',
  'Fading Wraith',
  'Flaring Minotaur',
  'Owasp-terror',
  'ArmoredElephant',
  'Kinetic Devourer',
  'Brood Parasite',
  'Stealthy Panther',
  'Entangling Vines',
  'Enson Plushie',
  'Reaving Drake',
  'Phantom Thief',
  'Spinecurse Beetle',
  'Foldabot',
  'Dwarven Shieldmaid',
  'Element Guardian of Harmony',
  'Starlight Poodle',
  'Fork-tail Wyrm',
  'Strangler Creeper',
  'Battle Ent',
  'Singed Serpent',
  'Talon Bat',
  'Serpent Berserker',
  'Wendigo Shifter',
  'Mythos Minotaur',
  'Corrupted Corpse',
  'Moonbeam Elk',
  'Bonewrought Dragonspawn',
  'Arboreal Gigantopithecus',
  'Lunar Moth',
  'Harrowing Harpy',
  'Grey Wolf',
  'Behemoth Knight',
  'Possessing Daemon',
  'Fel Drake Descendant',
  'Floating Candle Wisp',
  'Quicksilver Wyvern',
  'Burning Skull Spider',
  'Ao Oni',
  'Onyx Jaguar',
  'Crystal Guardian',
  'Soul Scourge',
  'Necrotic Skeletal Warrior',
  'Abyssal Tiger',
  'Tactilis Sorcerer',
  'Burning Gargoyle',
  'Stylish Sylph',
  'Flamemoore Mephit',
  'Blaze Berserker',
  'Pale Viper',
  'Netherworld Grizzly',
  'Slime Crab',
  'Thundercrusher Ram',
  'Cyclops Goliath',
  'Behemoth Vulture',
  'Glowgator',
  'Revenant Necromancer',
  'Freezing Rattlesnake',
  'Demonic Scorpion',
  'Blackbone Mammoth',
  'Winged Bear',
  'Smoldering Bat',
  'Shadowhawk',
  'Great Fox Spirit',
  'Direnettle Weed',
  'Human Mind Slaver',
  'Ascended Auto-Mech',
  'Glacial Salamander',
  'Rusting Golem',
  'Frost Ent',
  'Blaze Liger',
  'Unbound Elemental',
  'Electrifying Scout',
  'Darkforce Incarnate',
  'Soul-reaping Juggernaut',
  'Chimera Lord',
];

export default basicCreatures;
