export const basicEquipment = [
  'Short Sword',
  'Wooden Shield',
  'Leather Armor',
  'Healing Herbs',
  'Bow and Arrow',
  'Rejuvenating Elixir',
  'Longsword',
  'Battle Axe',
  'Steel Shield',
  'Plate Armor',
  'Magic Staff',
  'Amulet of Strength',
  'Throwing Knives',
  'Chainmail',
  'Wand of Fire',
  'Ruby Ring',
  'Iron Mace',
  'Divine Chalice',
  'Pike',
  'The Feathery Cap',
  'Spellbook',
  'Holy Symbol',
  'Elven Bow',
  'Drucheon of Vitality',
  'Iron Sword',
  'Adamant Shield',
  'Ghostblade',
  'Sapphire Ring',
  'Bow of Betrayal',
  'Bracing Shield',
  'Shadowed Dagger',
  'Soul Repulse',
  'Thunder Hammer',
  'Light Bracers',
  "Summoner's Gem",
  'Orb of Knowledge',
  'Frost Blade',
  'Quick Salve',
  'Collapsible Grappling Hook',
  'Vial of Poison',
  'Thunder Armbraces',
  'Smoke Bombs',
  'Ruby Necklace',
  'Distance Gauntlets',
  'Golden Armor',
];

export default basicEquipment;
