export const godTierSpells = [
  'Diablo Curse',
  'Divine Intervention',
  'Eldritch Sphere',
  'Godsend',
  'Apocalypse',
  'Doom Blade',
  "Pandora's Box",
  'Black Sun',
  'Heavenly Light',
  'Blood Sacrifice',
  'Void Rift',
  'Cosmic Ray',
  'Ghost Wall',
  'Rubicon Gate',
  'Teleport Z',
  'Celestial Arrow',
  'Tempest',
  'Enslave Demon',
  'Soul Visit',
  'Deadly Plague',
  'Baleful Jet',
  'Oracle Teleportation',
  'Divine Thunder',
  'Vampiric Torrent',
  'Covenant of Blood',
  'Holy Grail',
  'Apocalypse Blade',
  'Everwinter',
  'Chaos Reign',
  'Primal Force',
  'Mark of the Spiral',
  'Sigil of Summoning',
  'Exalted Miracle',
  'Cursed Oppression',
  'Sonorous Combusstion',
  'Blade Fury',
  'Divine Right',
  'Golden Hail',
  'Curse of Infamy',
  'Immolate',
  'Binding Barrier',
  'Dead Eye Strike',
  'Eclipse of Obliteration',
  'Vitrify',
  'Cacophonic Heaven',
  'Spacial Shifter',
];

export default godTierSpells;
