export const godTierCreatures = [
  "Chronomancer",
  "Sun Elemental",
  "Cthulhu",
  "Blaze Phoenix",
  "Nidhogg",
  "Maltheal - The Timeshifter",
  "Dragon Deity",
  "Tatiana - Queen of Dragons",
  "Null Entity",
  "Phoenix Emperor",
  "Norn’s Priestess",
  "Serendipity Angel",
  "Ancient Mara",
  "Onyx Sphinx",
  "Infernogorgon",
  "Infernum Beast",
  "Cerberus Andante",
  "Elven Champion",
  "Lornezo Ogaara - The Ruthless Scourge",
  "Scarab Ichor (also known as Scarabix)",
  "Hellion Squierarch",
  "Dhera I’ fharuos",
  "Crouch Corche",
  "Creature Rosheacalor",
  "Capito Abondiendang",
  "Australopithecized Slug Lion",
  "Lindmakeriva",
  "Galmraheratus",
  "Srachnursinear",
  "Vifisport",
  "Bunk Taillzin",
  "Rockamegvorack",
  "Galormidios Stoken",
  "Basnokscoracle",
  "Kragh Mestr",
  "Gertoeisiean Erahmark",
  "Mechagorazareal",
  "Lucifeanama",
  "Beatalistria Tekra",
  "Obsidianravzarion",
  "Kaleidisnappgarischon",
  "Gerbarithbroge",
  "Varniomantax",
  "Frauggeroncen",
  "Brutalidio",
  "Temptrewyfernajir",
  "Mortrendmeyorhurde",
  "Infernumphloriousae",
  "Aingholauphlesgrauphol",
  "Jenitzscheragon",
] as const;

export type GodTierCreature = typeof godTierCreatures[number];
